[package]
name = "fetchadd"
version = "0.1.0"
authors = ["ichiro ogata <i.ogata@aist.go.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
